### ISSUE TITLE
About Stems

### ISSUE THREAD

**Issue by linuxscout** [ibnmalik/golden-corpus-arabic#12]
من خلال عملي هذه الايام على التجذيع الخفيف، لاحظت أن مجذّع كرة الثلج يعطي نتائج جيدة جدا على المدونة الذهبية، لكنه يعجز مع مدونات أخرى،
وبعد مراجعة المدونة تبين لي:
- تنميط الأصول (تنميط الهمزات والألفات) هل هذا خيار أم خطأ؟
- بعض الأصول غير مناسب، مثلا يطلبون => يطلب والصحيح أن تعطي طلب
- الأصول الخاطئة تتطابق مع نتائج المجذع، وهذا يدل على أنه تم بناء المدونة باستخدام المجذع نفسه، وهذا يتطلب مراجعة يدوية، لتجنب هذه النتائج.
أحصيت 84 خطأ، مما يقلل النتائج ب7.39%
- المدونة فيها كثير من الأصول المتشابهة، مما يقلل من شمولها.

**Comment by assem-ch** [comment]
شكرا لك على الإقتراحات،

> تنميط الأصول (تنميط الهمزات والألفات) هل هذا خيار أم خطأ؟
- بالنسبة للهمزات هي مهملة في المجذع كخيار برمجي للوصول لأفضل تجميع، لكن لا يجب أن تظهر كذلك في المدونة لأن المدونة تعكس صحة الأصل لغويا
> بعض الأصول غير مناسب، مثلا يطلبون => يطلب والصحيح أن تعطي طلب
- تحويل يطلبون إلى يطلب أراه صائبا كجذع فتحويله الى طلب يعني عكس التصريف ويجب تطبيقه على كل الحالات,,شخصيا أراهم مستويين مختلفين للتجذيع إضافة إلى الجذر
> الأصول الخاطئة تتطابق مع نتائج المجذع، وهذا يدل على أنه تم بناء المدونة باستخدام المجذع نفسه، وهذا يتطلب مراجعة يدوية، لتجنب هذه النتائج.
> أحصيت 84 خطأ، مما يقلل النتائج ب7.39%

- أعلمنا بالجذوع الخاطئة وسنصححها
> المدونة فيها كثير من الأصول المتشابهة، مما يقلل من شمولها.
- هل تقترح توسيعها أو تقليل الأصول المتشابهة

**Comment by linuxscout** [comment]
>     بالنسبة للهمزات هي مهملة في المجذع كخيار برمجي للوصول لأفضل تجميع، لكن لا يجب أن تظهر كذلك في المدونة لأن المدونة تعكس صحة الأصل لغويا
تماما

>    أعلمنا بالجذوع الخاطئة وسنصححها
رفعتها على الموقع

>  هل تقترح توسيعها أو تقليل الأصول المتشابهة
صممت مشروعا لإثراء المدونات اسمه مكناز
يعمل على توليد ملف بيانات به الكلمة وأصلها وجذعها وجذرها ونوعا
يساعد كثيرا في بناء مدونة جيدة
[Miknaaz ](http://github.com/linuxscout/miknaaz)
